import React from "react";
import Sidebar from "@/components/dashboard/Sidebar";
import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "@/app/globals.css";
import { createClient } from "@/utils/supabase/server";
import { redirect } from "next/navigation";

const bricolageGrotesque = Bricolage_Grotesque({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-bricolage-grotesque",
});

export const metadata: Metadata = {
	title: "Dashboard - BoostBNB",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.png",
	},
};

const DashboardLayout = async ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {

	const supabase = await createClient();
	const { data: { user }, error } = await supabase.auth.getUser();

	if (error || !user) {
		redirect("/log-in");
	}

	return (
		<html lang="en">
			<body
				className={`bg-gray-100 text-gray-900 antialiased ${bricolageGrotesque.className}`}
			>
				<div className="flex flex-row min-h-screen bg-gray-200">
					<Sidebar />
					<div className="w-72 h-screen mx-10"></div>
					<main className="drawer-content w-full p-5">
						{children}
					</main>
				</div>
			</body>
		</html>
	);
};

export default DashboardLayout;
